version: "3.4"
services:
  whatoko-retail-front:
    restart: always
    environment:
      - NODE_ENV=development
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - frontend
    volumes:
      - ./:/usr/app

networks:
  frontend:
    driver: bridge
